// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egdtzhpgxlsometqmhgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZHR6aHBneGxzb21ldHFtaGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MjQ5OTQsImV4cCI6MjA1NzIwMDk5NH0.29HQ08hT3VjMgQo5ReI43yTNRb_pqRNHowS1MPIwRSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);